#!/usr/bin/env ruby

require 'optparse'
require 'ostruct'
require 'json'
require 'fileutils'

require_relative 'classes/arraystruct.rb'
require_relative 'classes/functions'
require_relative 'classes/os'
require_relative 'classes/library'
require_relative 'classes/fetch'
require_relative 'classes/unpack'
require_relative 'classes/build'
require_relative 'classes/install'
require_relative 'classes/platforms'
require_relative 'classes/exec'

currentDir = Dir.pwd

def showBanner
	return unless $options.show_banner
	puts <<BANNER
.__  ._____.  ___.         .__.__       .___ __                .__   
|  | |__\\_ |__\\_ |__  __ __|__|  |    __| _//  |_  ____   ____ |  |  
|  | |  || __ \\| __ \\|  |  \\  |  |   / __ |\\   __\\/  _ \\ /  _ \\|  |  
|  |_|  || \\_\\ \\ \\_\\ \\  |  /  |  |__/ /_/ | |  | (  <_> |  <_> )  |__
|____/__||___  /___  /____/|__|____/\\____ | |__|  \\____/ \\____/|____/
             \\/    \\/                    \\/                          
BANNER
end


def puts_banner text, col = 40, char = '*'
	puts ''.rjust(col, char)
	puts "*#{text.center(col -2 )}*"
	puts ''.rjust(col, char)
end

#######################################
### Options and parameters handling ###
#######################################

	DEFAULT_LIBRARIES_LIST = 'libraries.desc'
	$options = OpenStruct.new(
			:show_banner    => true,
			:libraries_list   => DEFAULT_LIBRARIES_LIST,
			:rebuild => false,
			:install_dir => "#{Dir.pwd}/#{`uname -s`.rstrip}/#{`uname -m`.rstrip}",
			:work_dir => "#{currentDir}/workdir",
			:platform => nil
	)

	@optionParser = OptionParser.new do |opts|
		opts.banner =  "Usage : #{File.basename $PROGRAM_NAME} [OPTION]"
		opts.separator 'Execute the build libraries listed by the given libraries list.'

		opts.separator ''
		opts.separator 'Global options'

		opts.on('-h', '--help', 'Shows this help.') do
			showBanner
			puts opts
			if $options.platform.respond_to? 'list_options'
				$options.platform.list_options
			end
			exit
		end

		opts.on('-r', '--rebuild', 'Rebuild all the lib instead of building the remaining libs.') do
			$options.rebuild = true
		end

		opts.on('--no-banner', 'Do not output the ASCII art banner.') do
			$options.show_banner = false
		end


		opts.on('-l', '--libraries-list', '=FILENAME', 'Libraries list to use.', "Default: #{DEFAULT_LIBRARIES_LIST}") do |file|
			$options.libraries_list = file
		end

		opts.separator ''
		opts.separator 'Platform options'
		opts.on('-P', '--list-platforms', 'Prints a list of available platforms.') do
			puts 'List of available platforms:'
			Platforms.list_classes.each do |g|
				puts "  #{g}"
			end
			exit 0
		end

		opts.on('-p', '--platform', '=PLATFORM', 'Name of the platform file to use.') do |platform|
			$options.platform = Platforms.get_platform platform
			$options.platform = $options.platform.new
			$options.platformName = platform
		end

		opts.on('--list-platform-options', 'Lists the options of the platform.') do
			unless $options.platform
				raise 'The platform has to be selected before listing its options.'
			end
			unless $options.platform.respond_to? 'list_options'
				raise 'The platform has no way to list its options.'
			end
			$options.platform.list_options
			exit 0
		end

	end
@optionParser.permute!

$options.platform.permute! if 	$options.platform




showBanner

libraries = []


#parsing libraries.desc
begin
	eval(File.open("#{$options.libraries_list}").read)
rescue Exception => e
	puts "Crashed while reading the libraries list!!!"
	puts e.backtrace
	puts e
end

###########################
### Settings resolution ###
###########################

workDir = $options.work_dir
buildedJsonPath = "#{workDir}/builded.json"
srcDir =  "#{currentDir}/workdir/src"
buildDir =  "#{currentDir}/workdir/build"




#############################
### Directory Preparation ###
#############################
buildedJson = []
if Dir.exist? workDir
	if $options.rebuild
		FileUtils.rm_rf buildDir
	else
		buildedJson = JSON.parse(File.read(buildedJsonPath)) if File.exist? buildedJsonPath
	end

end
	FileUtils.rm_rf buildDir if Dir.exist? buildDir

	FileUtils.mkdir_p $options.install_dir


	FileUtils.mkdir_p workDir
	FileUtils.mkdir_p srcDir
	FileUtils.mkdir_p buildDir

masterBuildOptions = nil
if defined? $options.platform.buildOptions and not $options.platform.buildOptions.nil?
	masterBuildOptions = $options.platform.buildOptions
else
	masterBuildOptions =  ArrayStruct.new()
end
masterBuildOptions.prefix = $options.install_dir

#################################
### Libraries build iteration ###
################################
libraries.each do |libraryDesc|
		next if buildedJson.include? libraryDesc
		buildOptions = masterBuildOptions.clone

		begin
			puts
			puts_banner libraryDesc
			puts

			library = Library.new
			library.fetch = Fetch.http
			library.prepareBuild = Functions.gotoSubDir
			library.build = Build.configure_make
			library.install = Install.make_install

			eval(File.open("#{libraryDesc}.desc").read)

### FETCH ###
			Dir.chdir srcDir
			if not File.exist? library.archive and library.fetch
				scriptSuccess = library.fetch.call library
				throw "Fetch script failed for #{library.name}" if not scriptSuccess
			end

### HASH ###
			archiveIsValid = true
			archiveIsValid = Functions.checkFileHash library.hash, library.archive if library.hash

			if not archiveIsValid
				throw "Hash for #{library.name} do not match with the given archive."
			end

### UNPACK ###
			FileUtils.mkdir_p buildDir
			if not library.unpack
				if(library.archive.include? '.tar' or library.archive.include? 'tgz')
					library.unpack = Unpack.tar
				elsif(library.archive.include? '.zip')
					library.unpack = Unpack.zip
				end
			end
			FileUtils.rm_rf "#{buildDir}/#{library.name}" if Dir.exist? "#{buildDir}/#{library.name}"
			FileUtils.mkdir_p "#{buildDir}/#{library.name}"
			scriptSuccess = library.unpack.call library, srcDir, "#{buildDir}/#{library.name}"
			throw "Unpack script failed for #{library.name}" if not scriptSuccess



### PREPARE BUILD ###
			Dir.chdir "#{buildDir}/#{library.name}"
			if library.prepareBuild
				scriptSuccess = library.prepareBuild.call library, buildOptions
				throw "PrepareBuild script failed for #{library.name}" if not scriptSuccess
			end

### BUILD ###
			if library.build
				scriptSuccess = library.build.call library, buildOptions
				throw "Build script failed for #{library.name}" if not scriptSuccess
			end

### INSTALL ###
			if library.install
				library.install = Install.make_install if not library.install
				scriptSuccess = library.install.call library, buildOptions
				throw "Install script failed for #{library.name}" if not scriptSuccess
			end


			Dir.chdir currentDir
			buildedJson << libraryDesc
			File.write(buildedJsonPath, JSON.generate(buildedJson))

		rescue Exception => e
			#FileUtils.rm_rf buildDir
			puts "Crashed while building #{libraryDesc}!!"
			puts e.backtrace
			puts e
			abort
		end
end

puts_banner 'Done!'
